name: flutter_shape_of_view_example
description: Demonstrates how to use the flutter_shape_of_view plugin.
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  kenburns_nullsafety: ^1.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  shape_of_view_null_safe:
    path: ../

flutter:

  uses-material-design: true

  assets:
    - assets/
