name: shape_of_view_null_safe
description: Give a custom shape to any flutter widget, Material Design 2 ready
version: 2.0.0
#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/awais-amjed/Flutter-ShapeOfView

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
  kenburns_nullsafety: ^1.0.1
flutter: