name: shape_of_view_null_safe
description: Give a custom shape to any flutter widget, Material Design 2 ready
version: 3.0.0
#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/awais-amjed/Flutter-ShapeOfView

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  kenburns_nullsafety: ^1.0.1
flutter:
